optimizer:
  type: AdamW
  kwargs:
    lr: 1e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 50
    initial_epochs: 5

dataset:
  train:
    _base_: cfgs/dataset_configs/SO_FT.yaml
    others:
      subset: train
      occlusion: False
      rotation: False
      noise: False
  val:
    _base_: cfgs/dataset_configs/SO_FT.yaml
    others:
      subset: test
      occlusion: False
      rotation: False
      noise: False

model:
  NAME: PointSO
  group_size: 32
  num_group: 512
  embed_dim: 512
  depth: 12
  drop_path_rate: 0.2
  num_heads: 8
  text_encoder: ViT-B/32

npoints: 10000
total_bs: 128
step_per_update: 1
max_epoch: 50